/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.table.DefaultTableModel;
import Clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author raulpenate
 */
public class panelMascotas extends javax.swing.JFrame {

    DefaultTableModel mdAnimal = new DefaultTableModel();

    public void generarContenido() {
        //Rellena tabla
        String[] columnaTabla = {"Nombre", "Animal", "Raza", "Naturaleza"};
        for (int i = 0; i < columnaTabla.length; i++) {
            mdAnimal.addColumn(columnaTabla[i]);
        }
        jtblAnimales.setModel(mdAnimal);
        //Rellena cbAnimal
        String[] datosAnimal = {Ave.class.getSimpleName(),
            Gato.class.getSimpleName(),
            Perro.class.getSimpleName(),
            Hamster.class.getSimpleName(),
            Pez.class.getSimpleName()};
        for (int i = 0; i < datosAnimal.length; i++) {
            cbEspecie.addItem(datosAnimal[i]);
        }
        //Rellena cbRaza
        String[] datosRaza = {};
        for (int i = 0; i < datosRaza.length; i++) {
            cbRaza.addItem(datosRaza[i]);
        }
        //Rellena cbNaturaleza
        String[] datosNaturaleza = {};
    }

    /**
     * Creates new form panel
     */
    public panelMascotas() {
        initComponents();
        generarContenido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        cbEspecie = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbRaza = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        cbNaturaleza = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnAcción = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAnimales = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comportamiento mascotas");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir mascota"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Especie");

        cbEspecie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEspecieItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Raza");

        cbRaza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRazaItemStateChanged(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Naturaleza");

        btnAcción.setText("Acción");
        btnAcción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcciónActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtxtNombre)
            .addComponent(cbEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(cbRaza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbNaturaleza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAcción, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNaturaleza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcción)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Mascotas"));

        jScrollPane1.setViewportView(jtblAnimales);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Rellenar tablas

    public void rellenarComboBox(String nombreCB, String datoUno, String datoDos, String datoTres, String datoCuatro, String datoCinco) {
        //Se ponen todos los datos en un array
        String[] datos = {datoUno, datoDos, datoTres, datoCuatro, datoCinco};
        //Depende a que CB vaya ahí se rellena
        switch (nombreCB) {
            case "Naturaleza":
                cbNaturaleza.removeAllItems();
                for (int i = 0; i < datos.length; i++) {
                    cbNaturaleza.addItem(datos[i]);
                }
                break;
            case "Raza":
                cbRaza.removeAllItems();
                for (int i = 0; i < datos.length; i++) {
                    cbRaza.addItem(datos[i]);
                }
                break;
        }
    }
    private void cbRazaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRazaItemStateChanged
        switch (cbEspecie.getSelectedItem() + "") {
            case "Ave":
                rellenarComboBox("Naturaleza", "Alegre", "Amable", "Agitada", "Alocada", "Modesta");
                break;
            case "Gato":
                rellenarComboBox("Naturaleza", "Alegre", "Miedoso", "Floja", "Sereno", "Afable");
                break;
            case "Perro":
                rellenarComboBox("Naturaleza", "Alegre", "Leal", "Floja", "Fuerte", "Dócil");
                break;
            case "Hamster":
                rellenarComboBox("Naturaleza", "Alegre", "Agitada", "Alocada", "Mansa", "Tímida");
                break;
            case "Pez":
                rellenarComboBox("Naturaleza", "Alegre", "Tímida", "Cauta", "Agitada", "Alocada");
                break;
        }
    }//GEN-LAST:event_cbRazaItemStateChanged

    private void cbEspecieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEspecieItemStateChanged

        switch (cbEspecie.getSelectedItem() + "") {
            case "Ave":
                rellenarComboBox("Raza", "Agapornis", "Cacatúa", "Loro", "Periquito", "Ninfa");
                break;
            case "Gato":
                rellenarComboBox("Raza", "Persa", "Siames", "Sphynx", "Siberiano", "Maine Coon");
                break;
            case "Perro":
                rellenarComboBox("Raza", "Siberiano", "Labrador", "Pug", "Bulldog", "Chow Chow");
                break;
            case "Hamster":
                rellenarComboBox("Raza", "Dorado", "Ruso", "Carabell", "Robo", "Chino");
                break;
            case "Pez":
                rellenarComboBox("Raza", "Cometa", "Ojo Dragón", "Celestial", "Payaso", "Ranchu");
                break;
        }
    }//GEN-LAST:event_cbEspecieItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            if (!jtxtNombre.getText().equals("")) {
                switch (cbEspecie.getSelectedItem() + "") {
                    case "Ave":
                        Ave oAve = new Ave();
                        oAve.setNombre(jtxtNombre.getText());
                        oAve.setEspecie(cbEspecie.getSelectedItem() + "");
                        oAve.setRaza(cbRaza.getSelectedItem() + "");
                        oAve.setNaturaleza(cbNaturaleza.getSelectedItem() + "");
                        //Se ordenan los datos de la tabla
                        String[] filaTablaAve = {
                            oAve.getNombre(),
                            oAve.getEspecie(),
                            oAve.getRaza(),
                            oAve.getNaturaleza()
                        };
                        mdAnimal.addRow(filaTablaAve);
                        jtblAnimales.setModel(mdAnimal);
                        break;
                    case "Gato":
                        Gato oGato = new Gato();
                        oGato.setNombre(jtxtNombre.getText());
                        oGato.setEspecie(cbEspecie.getSelectedItem() + "");
                        oGato.setRaza(cbRaza.getSelectedItem() + "");
                        oGato.setNaturaleza(cbNaturaleza.getSelectedItem() + "");
                        //Se ordenan los datos de la tabla
                        String[] filaTablaGato = {
                            oGato.getNombre(),
                            oGato.getEspecie(),
                            oGato.getRaza(),
                            oGato.getNaturaleza()
                        };
                        mdAnimal.addRow(filaTablaGato);
                        jtblAnimales.setModel(mdAnimal);
                        break;
                    case "Perro":
                        Perro oPerro = new Perro();
                        oPerro.setNombre(jtxtNombre.getText());
                        oPerro.setEspecie(cbEspecie.getSelectedItem() + "");
                        oPerro.setRaza(cbRaza.getSelectedItem() + "");
                        oPerro.setNaturaleza(cbNaturaleza.getSelectedItem() + "");
                        //Se ordenan los datos de la tabla
                        String[] filaTablaPerro = {
                            oPerro.getNombre(),
                            oPerro.getEspecie(),
                            oPerro.getRaza(),
                            oPerro.getNaturaleza()
                        };
                        mdAnimal.addRow(filaTablaPerro);
                        jtblAnimales.setModel(mdAnimal);
                        break;
                    case "Hamster":
                        Hamster oHamster = new Hamster();
                        oHamster.setNombre(jtxtNombre.getText());
                        oHamster.setEspecie(cbEspecie.getSelectedItem() + "");
                        oHamster.setRaza(cbRaza.getSelectedItem() + "");
                        oHamster.setNaturaleza(cbNaturaleza.getSelectedItem() + "");
                        //Se ordenan los datos de la tabla
                        String[] filaTablaHamster = {
                            oHamster.getNombre(),
                            oHamster.getEspecie(),
                            oHamster.getRaza(),
                            oHamster.getNaturaleza()
                        };
                        mdAnimal.addRow(filaTablaHamster);
                        jtblAnimales.setModel(mdAnimal);
                        break;
                    case "Pez":
                        Pez oPez = new Pez();
                        oPez.setNombre(jtxtNombre.getText());
                        oPez.setEspecie(cbEspecie.getSelectedItem() + "");
                        oPez.setRaza(cbRaza.getSelectedItem() + "");
                        oPez.setNaturaleza(cbNaturaleza.getSelectedItem() + "");
                        //Se ordenan los datos de la tabla
                        String[] filaTablaPez = {
                            oPez.getNombre(),
                            oPez.getEspecie(),
                            oPez.getRaza(),
                            oPez.getNaturaleza()
                        };
                        mdAnimal.addRow(filaTablaPez);
                        jtblAnimales.setModel(mdAnimal);
                        break;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAcciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcciónActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jtblAnimales.getSelectedRow();
        int column = 1;
        String tipoAnimal = jtblAnimales.getModel().getValueAt(selectedRowIndex, column) + "";
        switch (tipoAnimal) {
            case "Ave":
                Ave oAve = new Ave();
                oAve.accion();
                break;
            case "Gato":
                Gato oGato = new Gato();
                oGato.accion();
                break;
            case "Perro":
                Perro oPerro = new Perro();
                oPerro.accion();
                break;
            case "Hamster":
                Hamster oHamster = new Hamster();
                oHamster.accion();
                break;
            case "Pez":
                Pez oPez = new Pez();
                oPez.accion();
                break;
        }
    }//GEN-LAST:event_btnAcciónActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelMascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcción;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbEspecie;
    private javax.swing.JComboBox<String> cbNaturaleza;
    private javax.swing.JComboBox<String> cbRaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblAnimales;
    private javax.swing.JFormattedTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
